mybatis:
  configuration:  # setting配置
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.itgmd.pojo # 配置别名
  mapper-locations: classpath:/mapper/*.xml # mapperxml位置